version: '3.9'
services:
  lean-to-green-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:80"
    environment:
      - database:"database"
  database:
    image: mysql:5.7
    hostname: database
    environment:
      MYSQL_DATABASE: 'leantogreen'
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'sjoerd'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'sjoerd'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3307:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
    # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db: